import numpy as np

a = np.random.randint(4, size=(2, 3))
b = np.random.randint(4, size=(3, 2))
print('-------------')
print(a)
print('-------------')
print(b)
print('-------------')
print('array dot product')
print(a.shape, b.shape)
c = a.dot(b)
print('-------------')
print('array concat axis 0')
print(c)
print(c.shape)
d = np.concatenate((b, c), axis=0)
print('-------------')
print('array concat axis 1')
print(d)
print(d.shape)
e = np.concatenate((a, c), axis=1)
print('-------------')
print('indexing')
print(e)
print(e.shape)
f = e[1,1]
print('-------------')
print('scalar math')
print(f)
print(f.shape)
g = np.multiply(a, 22)
print('-------------')
print('vector math')
print(g)
print(g.shape)
h = np.add(a[:,:2], b[:2])
print('-------------')
print('statistic')
print(a[:,:2])
print(b[:2])
print(h)
print(h.shape)
print(np.mean(h))
print(a.T)
